pinch:
  2:
    in:
      sendkey: LEFTCTRL+KPMINUS # Zoom out
    out:
      sendkey: LEFTCTRL+KPPLUS # Zoom in

swipe:
  3:
    left:
      command: "xdotool key alt+Right" # History forward
    right: 
      command: "xdotool key alt+Left" # History back
    up:
      update:
        # sendkey: VOLUMEUP
        command: "xdotool key XF86AudioRaiseVolume"
    down:
      update:
        command: "xdotool key XF86AudioLowerVolume"
        # sendkey: VOLUMEDOWN
  4:
    left:
      command: "xdotool key ctrl+alt+Left" # Previous workstation
    right:
      command: "xdotool key ctrl+alt+Right" # Next workstation

threshold:
  pinch: 0.5

interval:
  pinch: 1.5

# rotate:
#   3:
#     clockwise:
#       update:
#         sendkey: VOLUMEUP
#     counterclockwise:
#       update:
#         sendkey: VOLUMEDOWN

plugin:
  inputs:
    libinput_command_input:
      enable-tap: true # click to tap
      enable-dwt: true # disable tap while typing
        # show-keycodes: true # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option
